name: Astro check

on:
  pull_request:
    branches: [main]

jobs:
  astro-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Setup node, yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn install

      - name: Astro check
        run: yarn check
