name: Check lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Use node v18, yarn
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint
