name: Check lint

on:
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2

      - name: Use node v18, yarn
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Run lint
        run: yarn lint
