name: Typecheck

on:
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Use node v15, npm 7
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: yarn install

      - name: Typecheck
        run: yarn typecheck
